name: Electron Build

on: 
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop
    types: [opened, reopened, review_requested]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.100
    - name: Install ElectronNET command line
      run: |
        dotnet tool install ElectronNET.CLI -g 
        echo "::add-path::$HOME/.dotnet/tools"
    - name: Build with electronize for Windows
      run: electronize build /target win
